### ISSUE TITLE
Deployment improvements

### ISSUE THREAD

**Issue by kenashkov** [AzonMedia/guzaba-platform#10]
- automatically import the database in the mysql container
- generate a new password for the admin user and display it during deployment

**Comment by taliezincho** [comment]
дай ми го това, ако искаш

**Comment by kenashkov** [comment]
A post install hook needs to be added to GuzabaPlatform. Please work in branch V_0_0_7.

To add a hook edit app/src/GuzabaPlatform/Platform/Application/Component.php and make it to implement https://github.com/AzonMedia/module-components-base/blob/master/src/Interfaces/PostInstallHookInterface.php

This method will be invoked when the GuzabaPlatform is installed with composer require and here the DB import must take place.

Please note - the app/src/GuzabaPlatform/Platform/Application/Component.php will be moved to app/src/GuzabaPlatform/Platform/Component.php in V_0_0_7 very soon.

**Comment by taliezincho** [comment]
commit в мастър, паролата не се сменя.
